language: ruby
rvm:
  - rvm 2.2.1
  - rvm 2.2.2

before_install:
  - sudo apt-get install postgresql-server-dev-9.1 libpq-dev

before_script:
  - psql -c 'create database authy2fa_sinatra;' -U postgres
  - psql -c 'create database authy2fa_sinatra_test;' -U postgres

install:
  - bundle

env:
  global:
    - AUTHY_API_KEY=TWILIOAPIKEY00000

